# Introduction to pandas

## Why use pandas?

*Addresses some shortcomings of NumPy:*

1.  Data is organized in *variables* and *observations*

2.  Each variable is permitted to have a *different* data type (integers, floats, strings, ...)

3.  Can select observations based on *labels* (e.g., time or date)

4.  Supports aggregation & reduction functions applied to *subsets* of data

5.  Many convenient data import / export functions

## Why not?

1.  NumPy is faster for low-level computing on homogeneous data
2.  pandas can consume lots of memory
3.  pandas can be slow with large data sets (millions of observations)

## Resources

- [pandas cheat sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

***
## Creating pandas data structures

pandas has two main data structures:

1.  [`Series`](https://pandas.pydata.org/docs/reference/api/pandas.Series.html):
    observations of a *single* variable.
2.  [`DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html):
    container for *several* variables.

*Example: Create Series from 1-dimensional NumPy array*

In [89]:
import numpy as np
import pandas as pd

# numpy array
data = np.arange(5, 10)

# Create a series from a numpy array
s = pd.Series(data)
s

0    5
1    6
2    7
3    8
4    9
dtype: int64

*Example: Create DataFrame from NumPy array*

-   We can create 2-dimensional arrays from 1-dimensional ones with 
    [`reshape()`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [90]:
data2d = np.arange(15).reshape(5, 3)

# Create a DataFrame from 2d array
df = pd.DataFrame(data2d, columns=['A', 'B', 'C'])
df

    A   B   C
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

*Example: Create DataFrame with non-homogeneous data from dictionary*

In [91]:
import numpy as np
import pandas as pd

# Create demo data for two individuals:

# Names (strings)
names = ["Alice", "Bob"]

# Birth dates (datetime objects)
bdates = pd.to_datetime(["1985-01-01", "1997-05-12"])

# Incomes (floats)
incomes = np.array([600000, np.nan])  # code missing income as NaN

In [92]:
# Create a DataFrame from a dict
df = pd.DataFrame({'name': names, 'bdate': bdates, 'income': incomes})
df

    name      bdate    income
0  Alice 1985-01-01  600000.0
1    Bob 1997-05-12       NaN

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Create a pandas `Series` which contains the characters `'a'`, `'b'`, and `'c'`.
</div>
<span style="display: none;">YourTurnEnd</span>

In [93]:
# numpy array
lst = ['a', 'b', 'c']

# Create a series from a numpy array
s = pd.Series(lst)
s

df = pd.DataFrame(lst, columns=['Characters'])
df

  Characters
0          a
1          b
2          c

***
## Loading data with pandas

The most important input/output functions are:

-   [`read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html),
    [`to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html):
    Read or write CSV text files.
-   [`read_fwf()`](https://pandas.pydata.org/docs/reference/api/pandas.read_fwf.html):
    Read data with fixed field widths, i.e., text data
    that does not use delimiters to separate fields.
-   [`read_excel()`](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html),
    [`to_excel()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html):
    Read or write Excel spreadsheets.
-   [`read_stata()`](https://pandas.pydata.org/docs/reference/api/pandas.read_stata.html),
    [`to_stata()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_stata.html):
    Read or write Stata's `.dta` files.
-   [`read_json()`](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html),
    [`to_json()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html#pandas.DataFrame.to_json):
    Read or write JSON files (lightweight machine-readable text files, often produced by LLMs)

*Example: Load data using `read_csv()`*

In [94]:
# Use files in the local data/ directory
DATA_PATH = "../../data"

In [95]:
file = f'{DATA_PATH}/FRED/FRED_annual.csv'
file

'../../data/FRED/FRED_annual.csv'

In [96]:
data = pd.read_csv(file, sep=',')

data

    Year      GDP    CPI  UNRATE  FEDFUNDS  INFLATION
0   1954   2877.7   26.9     5.6       1.0        NaN
1   1955   3083.0   26.8     4.4       1.8       -0.4
2   1956   3148.8   27.2     4.1       2.7        1.5
3   1957   3215.1   28.1     4.3       3.1        3.3
4   1958   3191.2   28.9     6.8       1.6        2.8
5   1959   3412.4   29.2     5.4       3.3        1.0
6   1960   3500.3   29.6     5.5       3.2        1.4
7   1961   3590.1   29.9     6.7       2.0        1.0
8   1962   3810.1   30.3     5.6       2.7        1.3
9   1963   3976.1   30.6     5.6       3.2        1.0
10  1964   4205.3   31.0     5.2       3.5        1.3
11  1965   4478.6   31.5     4.5       4.1        1.6
12  1966   4773.9   32.5     3.8       5.1        3.2
13  1967   4904.9   33.4     3.8       4.2        2.8
14  1968   5145.9   34.8     3.6       5.7        4.2
15  1969   5306.6   36.7     3.5       8.2        5.5
16  1970   5316.4   38.8     5.0       7.2        5.7
17  1971   5491.4   40.5     6.0       4.7        4.4
18  1972   5780.0   41.8     5.6       4.4        3.2
19  1973   6106.4   44.4     4.9       8.7        6.2
20  1974   6073.4   49.3     5.6      10.5       11.0
21  1975   6060.9   53.8     8.5       5.8        9.1
22  1976   6387.4   56.9     7.7       5.0        5.8
23  1977   6682.8   60.6     7.0       5.5        6.5
24  1978   7052.7   65.2     6.1       7.9        7.6
25  1979   7276.0   72.6     5.9      11.2       11.3
26  1980   7257.3   82.4     7.2      13.4       13.5
27  1981   7441.5   90.9     7.6      16.4       10.3
28  1982   7307.3   96.5     9.7      12.3        6.2
29  1983   7642.3   99.6     9.6       9.1        3.2
30  1984   8195.3  103.9     7.5      10.2        4.3
31  1985   8537.0  107.6     7.2       8.1        3.6
32  1986   8832.6  109.7     7.0       6.8        2.0
33  1987   9137.7  113.6     6.2       6.7        3.6
34  1988   9519.4  118.3     5.5       7.6        4.1
35  1989   9869.0  123.9     5.3       9.2        4.7
36  1990  10055.1  130.7     5.6       8.1        5.5
37  1991  10044.2  136.2     6.8       5.7        4.2
38  1992  10398.0  140.3     7.5       3.5        3.0
39  1993  10684.2  144.5     6.9       3.0        3.0
40  1994  11114.6  148.2     6.1       4.2        2.6
41  1995  11413.0  152.4     5.6       5.8        2.8
42  1996  11843.6  156.9     5.4       5.3        3.0
43  1997  12370.3  160.5     4.9       5.5        2.3
44  1998  12924.9  163.0     4.5       5.4        1.6
45  1999  13543.8  166.6     4.2       5.0        2.2
46  2000  14096.0  172.2     4.0       6.2        3.4
47  2001  14230.7  177.0     4.7       3.9        2.8
48  2002  14472.7  179.9     5.8       1.7        1.6
49  2003  14877.3  184.0     6.0       1.1        2.3
50  2004  15449.8  188.9     5.5       1.3        2.7
51  2005  15988.0  195.3     5.1       3.2        3.4
52  2006  16433.1  201.6     4.6       5.0        3.2
53  2007  16762.4  207.3     4.6       5.0        2.8
54  2008  16781.5  215.3     5.8       1.9        3.9
55  2009  16349.1  214.6     9.3       0.2       -0.3
56  2010  16789.8  218.1     9.6       0.2        1.6
57  2011  17052.4  224.9     8.9       0.1        3.1
58  2012  17442.8  229.6     8.1       0.1        2.1
59  2013  17812.2  233.0     7.4       0.1        1.5
60  2014  18261.7  236.7     6.2       0.1        1.6
61  2015  18799.6  237.0     5.3       0.1        0.1
62  2016  19141.7  240.0     4.9       0.4        1.3
63  2017  19612.1  245.1     4.4       1.0        2.1
64  2018  20193.9  251.1     3.9       1.8        2.4
65  2019  20715.7  255.7     3.7       2.2        1.8
66  2020  20284.5  258.9     8.1       0.4        1.3
67  2021  21532.4  271.0     5.4       0.1        4.7
68  2022  22075.9  292.6     3.6       1.7        8.0
69  2023  22723.7  304.7     3.6       5.0        4.1
70  2024  23358.4  313.7     4.0       5.1        3.0
71  2025  23850.4  322.0     4.3       4.2        2.6

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the pandas functions listed above to import data from the following files located in the `data` folder:

1. `titanic.csv`
2. `FRED/FRED_annual.xlsx`

To load Excel files, you need to have the package `openpyxl` installed.
</div>
<span style="display: none;">YourTurnEnd</span>

In [97]:
titanic = f'{DATA_PATH}/titanic.csv'
titanic_data = pd.read_csv(titanic, sep=',')
titanic_data

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q

In [98]:
xlsx = f'{DATA_PATH}/FRED/FRED_annual.xlsx'
xlsx_data = pd.read_excel(xlsx)
xlsx_data

    Year      GDP    CPI  UNRATE  FEDFUNDS  INFLATION
0   1954   2877.7   26.9     5.6       1.0        NaN
1   1955   3083.0   26.8     4.4       1.8  -0.371747
2   1956   3148.8   27.2     4.1       2.7   1.492537
3   1957   3215.1   28.1     4.3       3.1   3.308824
4   1958   3191.2   28.9     6.8       1.6   2.846975
5   1959   3412.4   29.2     5.4       3.3   1.038062
6   1960   3500.3   29.6     5.5       3.2   1.369863
7   1961   3590.1   29.9     6.7       2.0   1.013514
8   1962   3810.1   30.3     5.6       2.7   1.337793
9   1963   3976.1   30.6     5.6       3.2   0.990099
10  1964   4205.3   31.0     5.2       3.5   1.307190
11  1965   4478.6   31.5     4.5       4.1   1.612903
12  1966   4773.9   32.5     3.8       5.1   3.174603
13  1967   4904.9   33.4     3.8       4.2   2.769231
14  1968   5145.9   34.8     3.6       5.7   4.191617
15  1969   5306.6   36.7     3.5       8.2   5.459770
16  1970   5316.4   38.8     5.0       7.2   5.722071
17  1971   5491.4   40.5     6.0       4.7   4.381443
18  1972   5780.0   41.8     5.6       4.4   3.209877
19  1973   6106.4   44.4     4.9       8.7   6.220096
20  1974   6073.4   49.3     5.6      10.5  11.036036
21  1975   6060.9   53.8     8.5       5.8   9.127789
22  1976   6387.4   56.9     7.7       5.0   5.762082
23  1977   6682.8   60.6     7.0       5.5   6.502636
24  1978   7052.7   65.2     6.1       7.9   7.590759
25  1979   7276.0   72.6     5.9      11.2  11.349693
26  1980   7257.3   82.4     7.2      13.4  13.498623
27  1981   7441.5   90.9     7.6      16.4  10.315534
28  1982   7307.3   96.5     9.7      12.3   6.160616
29  1983   7642.3   99.6     9.6       9.1   3.212435
30  1984   8195.3  103.9     7.5      10.2   4.317269
31  1985   8537.0  107.6     7.2       8.1   3.561116
32  1986   8832.6  109.7     7.0       6.8   1.951673
33  1987   9137.7  113.6     6.2       6.7   3.555150
34  1988   9519.4  118.3     5.5       7.6   4.137324
35  1989   9869.0  123.9     5.3       9.2   4.733728
36  1990  10055.1  130.7     5.6       8.1   5.488297
37  1991  10044.2  136.2     6.8       5.7   4.208110
38  1992  10398.0  140.3     7.5       3.5   3.010279
39  1993  10684.2  144.5     6.9       3.0   2.993585
40  1994  11114.6  148.2     6.1       4.2   2.560554
41  1995  11413.0  152.4     5.6       5.8   2.834008
42  1996  11843.6  156.9     5.4       5.3   2.952756
43  1997  12370.3  160.5     4.9       5.5   2.294455
44  1998  12924.9  163.0     4.5       5.4   1.557632
45  1999  13543.8  166.6     4.2       5.0   2.208589
46  2000  14096.0  172.2     4.0       6.2   3.361345
47  2001  14230.7  177.0     4.7       3.9   2.787456
48  2002  14472.7  179.9     5.8       1.7   1.638418
49  2003  14877.3  184.0     6.0       1.1   2.279044
50  2004  15449.8  188.9     5.5       1.3   2.663043
51  2005  15988.0  195.3     5.1       3.2   3.388036
52  2006  16433.1  201.6     4.6       5.0   3.225806
53  2007  16762.4  207.3     4.6       5.0   2.827381
54  2008  16781.5  215.3     5.8       1.9   3.859141
55  2009  16349.1  214.6     9.3       0.2  -0.325128
56  2010  16789.8  218.1     9.6       0.2   1.630941
57  2011  17052.4  224.9     8.9       0.1   3.117836
58  2012  17442.8  229.6     8.1       0.1   2.089818
59  2013  17812.2  233.0     7.4       0.1   1.480836
60  2014  18261.7  236.7     6.2       0.1   1.587983
61  2015  18799.6  237.0     5.3       0.1   0.126743
62  2016  19141.7  240.0     4.9       0.4   1.265823
63  2017  19612.1  245.1     4.4       1.0   2.125000
64  2018  20193.9  251.1     3.9       1.8   2.447980
65  2019  20715.7  255.7     3.7       2.2   1.831939
66  2020  20284.5  258.9     8.1       0.4   1.251467
67  2021  21532.4  271.0     5.4       0.1   4.673619
68  2022  22075.9  292.6     3.6       1.7   7.970480
69  2023  22723.7  304.7     3.6       5.0   4.135338
70  2024  23358.4  313.7     4.0       5.1   2.953725
71  2025  23850.4  322.0     4.3       4.2   2.645840

***
## Viewing data

Methods for inspecting (parts of) a `DataFrame`:

- [`info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html):
  print observation counts, columns, and data types
- [`head()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html):
  print the first few rows
- [`tail()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html):
  print the last few rows
- [`describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html):
  print summary statistics for *numerical* data
- [`value_counts()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html):
  tabulate observation counts for categorical data

- [`set_option()`](https://pandas.pydata.org/docs/reference/api/pandas.set_option.html):
  set pandas display options

*Example: Titanic data set*

Columns present in the file `titanic.csv`:

1.  `PassengerId`
2.  `Survived`: indicator whether the person survived
3.  `Pclass`: accommodation class (first, second, third)
4.  `Name`: Name of passenger (last name, first name)
5.  `Sex`: `male` or `female`
6.  `Age`
7.  `Ticket`: Ticket number
8.  `Fare`: Fare in pounds
9.  `Cabin`: Deck + cabin number
10. `Embarked`: Port at which passenger embarked:
    `C` - Cherbourg, `Q` - Queenstown, `S` - Southampton

*Example: Viewing data with `head()` and `tail()`*

### Setting pandas display options

- Use [`set_option()`](https://pandas.pydata.org/docs/reference/api/pandas.set_option.html) to configure how much data pandas displays by default.

In [99]:
# Set the line width to 120 characters (default: 80)
pd.set_option("display.width", 120)
# Show up to 100 rows (default: 60)
pd.set_option("display.max_rows", 100)

### Descriptive statistics

- Use [`describe()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) to compute summary statistics for numerical data.
- Use [`value_counts()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) to tabulate observation counts for categorical data.
- Use [`info()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html) to tabulate data types and number of non-null rows.

*Example: print summary statistics for numerical data*

In [100]:
titanic_data.describe()

       PassengerId    Survived      Pclass         Age        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118   32.204208
std     257.353842    0.486592    0.836071   14.526497   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    7.910400
50%     446.000000    0.000000    3.000000   28.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000  512.329200

*Example: tabulate the number of men and women in the data set*

In [101]:
titanic_data['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

*Example: Inspect data types with `info()`*

In [102]:
titanic_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   Ticket       891 non-null    str
 7   Fare         891 non-null    float64
 8   Cabin        204 non-null    str
 9   Embarked     889 non-null    str
dtypes: float64(2), int64(3), str(5)
memory usage: 69.7 KB

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Using the Titanic data set:

1. Tabulate the number of passengers by boarding port (variable `Embarked`).
2. Count the observations with a missing value for `Embarked`.

   *Hint:* `value_counts()` excludes missing values by default. Use `dropna=False`
   to include them in the table, or use `isna().sum()` to count them separately.
</div>
<span style="display: none;">YourTurnEnd</span>

In [103]:
titanic_data['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [104]:
titanic_data['Embarked'].value_counts(dropna=False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [105]:
titanic_data['Embarked'].isna().sum()

np.int64(2)

***
## Indexing

pandas supports two types of indexing:

1.  Indexing by position (same as Python containers and NumPy arrays)
2.  Indexing by label, i.e., by the values assigned to the row or column *index*.

pandas indexing is performed either by using brackets `[]`, or by using
[`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)
for label indexing, or
[`.iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)
for positional indexing.

Indexing via `[]` can be somewhat confusing:

-   specifying `df['name']` returns the column `name` as a `Series` object.
-   specifying a range such as `df[5:10]` returns the *rows*
    associated with the *positions* 5,...,9.

    **Recommendation:** Don't use this, there are less confusing ways to select rows.

*Example: Selecting a single column*

-   Select column `'Name'` from Titanic data set

In [106]:
titanic_data['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                          Graham, Miss Margaret Edith
888              Johnston, Miss Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

*Example: Selecting multiple columns*

-   Select columns `'Name'` and `'Sex'` from Titanic data set
-   Need to specify multiple columns as `list`

In [107]:
titanic_data[['Name', 'Sex']]

                                                  Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                                Heikkinen, Miss Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                        Graham, Miss Margaret Edith  female
888            Johnston, Miss Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

***
### Creating and manipulating indices


Three main methods to create/manipulate indices:

1.   Create a new `Series` or `DataFrame` object with a custom index
    using the `index` argument.
2.   [`set_index(keys=['column1', ...])`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)
    uses the values of `column1`
    and optionally additional columns as indices, discarding the current index.
3.   [`reset_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html) 
    resets the index to its default value, a sequence
    of increasing integers starting at 0.

#### Creating custom indices

*Example: Create `Series` with custom index*

In [108]:
import pandas as pd

s = pd.Series([0, 1, 2], index=['a', 'b', 'c'])
s

a    0
b    1
c    2
dtype: int64

#### Manipulating indices

-   Default: return a new object; leave the original unchanged.
-   Assign the result back, or use `inplace=True`.
-   With `inplace=True`, both methods return `None`.
-   `set_index()`: `DataFrame` only; `reset_index()`: also `Series`.

*Example: Set DataFrame index from column*

-   Use the
    [`set_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)
    method
-   Optionally specify `append=True` to add as *additional* index levels

In [109]:
# Create demo DataFrame
import pandas as pd

df = pd.DataFrame({"A": [10, 20, 30], "B": ["a", "b", "c"]})

In [110]:
df

    A  B
0  10  a
1  20  b
2  30  c

In [111]:
df.set_index('B')

    A
B
a  10
b  20
c  30

In [112]:
df

    A  B
0  10  a
1  20  b
2  30  c

*Example: Reset DataFrame index*

-   Use the
    [`reset_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html)
    method
-   Use `drop=True` to discard the old index; otherwise, it becomes a column.

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Read in the following data files from the `data/FRED` folder and manipulate the
`DataFrame` index:

1. Read in the file `FRED_annual.csv` and set the column `Year` as the index.
2. Read in the file `FRED_monthly.csv` and set the columns `Year` and `Month` as the
   index.

Perform the tasks using `inplace=False` and `inplace=True`. What's the difference?

Restore the original (default) index after you are done.
</div>
<span style="display: none;">YourTurnEnd</span>

In [113]:
file_annual = f'{DATA_PATH}/FRED/FRED_annual.csv'
file_monthly = f'{DATA_PATH}/FRED/FRED_monthly.csv'

df_annual = pd.read_csv(file_annual)
df_monthly = pd.read_csv(file_monthly)

In [114]:
df_annual = df_annual.set_index('Year')

In [115]:
df_monthly = df_monthly.set_index(['Year', 'Month'])

In [116]:
df_monthly.loc[2025, 8]

DATE        2025-08-01
CPI              323.3
UNRATE             4.3
FEDFUNDS           4.3
REALRATE           1.5
LFPART            62.3
Name: (2025, 8), dtype: object

***
### Selecting elements

Recommended rules for indexing:

1.  Use `df['name']` to select *columns*.
2.  Use
    [`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)
    to select by label.
3.  Use
    [`.iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)
    to select by position.

*Demo data set used for this section:*

In [119]:
# Create demo data with 3 columns and 5 rows

# Column labels
columns = ["X", "Y", "Z"]
# Row labels
rows = ["a", "b", "c", "d", "e"]

values = np.arange(len(rows))

# Create data dictionary using a list comprehension
data = {col: [f"{col}{val}" for val in values] for col in columns}

# Create DataFrame from dictionary
df = pd.DataFrame(data, index=rows)

In [120]:
df

    X   Y   Z
a  X0  Y0  Z0
b  X1  Y1  Z1
c  X2  Y2  Z2
d  X3  Y3  Z3
e  X4  Y4  Z4

**Selection by label**

-   Use
    [`.loc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)
    to select rows and/or columns *by label*
-   Can use *slicing* where last element is *included*

In [123]:
df.loc['a':'c', 'X':'Y']

    X   Y
a  X0  Y0
b  X1  Y1
c  X2  Y2

**Selection by position**

-   Use
    [`.iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)
    to select rows and/or columns *by position*
-   Reset the demo index to default integers before the exercise.

In [125]:
df.iloc[0:2, 0:2]

    X   Y
a  X0  Y0
b  X1  Y1

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Using the DataFrame `df` we created above:

1. Compare `df.loc[0:3]` and `df.iloc[0:3]`. How many rows does each select?
   Predict the results before running the code.
2. Compare `df.loc[-1]` and `df.iloc[-1]`. What happens in each case, and why?
</div>
<span style="display: none;">YourTurnEnd</span>

**Boolean indexing**

-   Select elements based on whether some condition is true
-   Works with `[]` and `.loc[]`

*Example: Boolean indexing with Titanic data*

- Select all rows of passengers who embarked in Southampton (`'Embarked'` equals `'S'`)

In [127]:
file = f'{DATA_PATH}/titanic.csv'
df = pd.read_csv(file)

In [128]:
# Create a boolean mask selecting all with Embarked == S
mask = df['Embarked'] == 'S'

In [134]:
# Use mask to select observations where mask is true
df[df['Embarked'] == 'S']

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S

*Example: Multiple conditions with logical and/or*

- Select all rows of *male* passengers (`'Sex'` equals `'male'`) who embarked in Southampton (`'Embarked'` equals `'S'`)

In [137]:
df[(df['Sex'] == 'male') & (df['Embarked'] == 'S')]

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,349909,21.0750,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,A/5. 2151,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,349217,7.8958,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,349257,7.8958,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S

*Example: Using `isin()`*

- Select all rows of passengers who embarked either in Southampton or Queenstown
  (`'Embarked'` equals `'S'` or `'Q'`)

*Example: Using `query()`*

- Select all rows of passengers who embarked in Southampton (`'Embarked'` equals `'S'`) and are older than 70

In [143]:
df.query('Embarked == "S" & Age > 70')
df.query('Embarked == "S" | Age > 70')

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Load the Titanic passenger data set `data/titanic.csv` and select the following subsets of data:

1. Select the 10th to 20th (inclusive) rows of the `DataFrame`.
2. Using `query()`, select the sub-sample of female passengers aged 30 to 40. Display
   only the columns `Name`, `Age`, and `Sex` (in that order).
3. Repeat the last exercise without using `query()`.
4. Select all men who embarked in Queenstown or Cherbourg.
</div>
<span style="display: none;">YourTurnEnd</span>

***
## Working with time series data

-   pandas indices can be date or datetime data types
-   Use
    [`date_range()`](https://pandas.pydata.org/docs/reference/api/pandas.date_range.html)
    to create a range of dates
-   Use
    [`to_datetime()`](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html)
    to convert existing data to datetime format

*Example: Creating a date index*

-   Create a demo data set of daily observations for the first 3 months of 2026

In [118]:
# Start and end dates used for demo data set
start = "2026-01-01"
end = "2026-03-31"

*Example: Select particular date*

-   Select observation from January 1, 2026

*Example: Select date range*

- Select first 5 days in January 2026

*Example: Use a partial index*

- Select all of January 2026

### Lags, differences, and other useful transformations

Methods to shift/difference observations along time dimension:

- [`shift()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.shift.html):
  shifts values to create leads/lags; keeps the index unchanged by default
- [`diff()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.diff.html):
  computes absolute differences over a given period
- [`pct_change()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html):
  computes fractional changes; multiply by 100 for percentages

<div style="padding: 0.8em 1em 0.5em 1em; border: 2pt solid #1d91c0;">
<p style="font-weight: bold; font-size: 1.5em; color: #1d91c0;">Your turn</p>

Use the data from the `data/FRED` folder to perform the following tasks:

1. Read in the file `FRED_annual.csv` and set the column `Year` as the index.
2. Compute annual inflation as the percentage change of the consumer price
   index (column `CPI`). Use `pct_change()` and multiply by 100 to express
   inflation as a percentage.
</div>
<span style="display: none;">YourTurnEnd</span>